# Generated by Django 3.2.16 on 2022-12-17 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('text', models.TextField(max_length=250, verbose_name='Text')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('published_date', models.DateTimeField(verbose_name='published date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_post.category')),
            ],
        ),
    ]
